# Generated by Django 4.2.11 on 2026-06-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Identifier (e.g., 'get_weather')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Instructions for Gemma 4 on when to use this API.')),
                ('url', models.URLField(help_text='The actual REST API endpoint to call.')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10)),
                ('parameters_schema', models.JSONField(blank=True, default=dict, help_text='OpenAPI JSON parameters schema.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
