# Generated by Django 6.0.6 on 2026-06-07 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_prompt', models.TextField(help_text='The exact question the user asked.')),
                ('tool_called', models.CharField(blank=True, help_text='Which database tool was triggered?', max_length=100, null=True)),
                ('tool_arguments', models.JSONField(blank=True, help_text='The exact arguments Gemma passed to the tool.', null=True)),
                ('tool_raw_response', models.JSONField(blank=True, help_text='The raw JSON data returned by the remote API.', null=True)),
                ('final_response', models.TextField(blank=True, help_text='The final textual response sent to the user.', null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error')], default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
